### ISSUE TITLE
Script not working anymore

### ISSUE THREAD

**Issue by baumannchristian** [carojkov/salesforce-export-downloader#2]
Hi,

since 2 weeks or so, the script is not working anymore, this is the output I get:

> Logging in...
> Downloading index...
>   All urls:
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> <html>
> <head>
>     <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
> 
> 
> 
> 
> 
> <script>
> if (this.SfdcApp && this.SfdcApp.projectOneNavigator) { SfdcApp.projectOneNavigator.handleRedirect('https://login.salesforce.com/?ec=302&startURL=%2Fservlet%2Fservlet.OrgExport'); }  else 
> if (window.location.replace){ 
> window.location.replace('https://login.salesforce.com/?ec=302&startURL=%2Fservlet%2Fservlet.OrgExport');
> } else {;
> window.location.href ='https://login.salesforce.com/?ec=302&startURL=%2Fservlet%2Fservlet.OrgExport';
> } 
> </script>
> 
> </head>
> 
> 
> </html>
> 
> 
> 
> 
> 
> 
> <script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>
> 			
> </body>
> </html>
> 
> 
> 
> 
> C:/Users/christian.baumann/RubymineProjects/salesforce-export-downloader-master/salesforce-backup.rb:61:in `file_name': undefined method `[]' for nil:NilClass (NoMethodError)
> 	from C:/Users/christian.baumann/RubymineProjects/salesforce-export-downloader-master/salesforce-backup.rb:201:in `block in <top (required)>'
> 	from C:/Users/christian.baumann/RubymineProjects/salesforce-export-downloader-master/salesforce-backup.rb:200:in `each'
> 	from C:/Users/christian.baumann/RubymineProjects/salesforce-export-downloader-master/salesforce-backup.rb:200:in `<top (required)>'
> 	from -e:1:in `load'
> 	from -e:1:in `<main>'
> 
> Process finished with exit code 1

Thx a lot,
Christian

**Comment by carojkov** [comment]
Hi Christian,

Unfortunately I don't have access to salesforce and no longer can provide
fixes.

Best Regards,
Alex


On Tue, Dec 12, 2017 at 1:48 AM, Christian Baumann <notifications@github.com

**Comment by jeffgates** [comment]
I had the same problem, I changed sales force site URL and it fixed the issue.

**Comment by jeffgates** [comment]
When we run the back with the ondemand tools we get the history files, when I use the ruby script the history files are not there. 

--Jeff

**Comment by baumannchristian** [comment]
Thanks a lot @jeffgates, that indeed worked for me as well! :-)

**Comment by okram999** [comment]
@baumannchristian - how about closing the issue?

**Comment by RPGillespie6** [comment]
This script works as of March 2022. I had to change sales_force_site in the config to use `?.my.salesforce.com` format. Note that lightning UI format will not work.
